core/urls.py
from django.urls import path
from .views import (
    HomeView,
    EmployeeListView,
    EmployeeDetailView,
    EmployeeCreateView,
    EmployeeUpdateView,
    EmployeeDeleteView,

    DepartmentListView,
)
from .views import department_create

app_name = "core"

urlpatterns = [
    #path('', views.index, name='index'),
    path('', HomeView.as_view(), name='home'),
    path('employee', EmployeeListView.as_view(), name='employee'),
    path('employee/create/', EmployeeCreateView.as_view(), name='employee-add'),
    path('employee/update/<int:pk>/', EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee/delete/<int:pk>/', EmployeeDeleteView.as_view(), name='employee-delete'),
    path('employee/<int:pk>/', EmployeeDetailView.as_view(), name="employee-detail"),

    path('department', DepartmentListView.as_view(), name='department-list'),
    path('department/create/', department_create, name='department-create'),

]

hra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

handler404 = 'core.views.error_404_view'

urlpatterns = urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Change the Admin Panel Header
admin.site.site_header = "HR & Administration"
admin.site.index_title = "Management"

templates/department_create.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}

{% block content %}
<div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <h3 class="text-gray-900 text-xl leading-tight font-medium mb-2">Create Department</h3>
    <div class="mt-8 max-w-md">

<!--            <form action="" method="post" enctype="multipart/form-data">-->

<!--                {% csrf_token %}-->
<!--                {{ form|crispy }}-->

<!--                <input type="submit" value="Save" class="inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out"/>-->

<!--                <a href="{% url 'core:employee' %}" class="inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out">Cancel</a>-->
<!--            </form>-->

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Save" class="inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out"/>
                <a href="{% url 'core:department-list' %}" class="inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out">Cancel</a>

            </form>

    </div>
</div>
{% endblock content %}

templates/department_list.html
{% extends "base.html" %}

{% block content %}
    <header class="bg-white shadow">
        <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold tracking-tight text-gray-900">Department List</h1>
        </div>
    </header>
    <main>
        <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
            <!-- Replace with your content -->
            <div class="inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8 flex flex-col">

                        {% if messages %}
                        {% for message in messages %}

                        <div class="bg-green-100 rounded-lg py-5 px-6 mb-3 text-base text-green-700 inline-flex items-center w-full" role="alert">
                          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path fill="currentColor" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path>
                          </svg>
                          {{ message|safe }}
                        </div>
                        {% endfor %}
                        {% endif %}

                        <div class="overflow-hidden">
                            <a href="{% url 'core:department-create' %}" type="button" class="inline-block px-6 py-2.5 bg-blue-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-500 hover:shadow-lg focus:bg-blue-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-600 active:shadow-lg transition duration-150 ease-in-out">
+ Add Department
</a>
                            <table class="min-w-full text-center">
                                <thead class="border-b bg-gray-500">
                                <tr>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Department
                                    </th>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Description
                                    </th>

                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Action
                                    </th>
                                </tr>
                                </thead class="border-b">
                                <tbody>
                                {% for department in object_list %}
                                <tr class="bg-white border-b">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ department.name }}
                                    </td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ department.description }}
                                    </td>

                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        <a href="{{ employee.get_update_url }}" class="inline-block px-6 py-2 border-2 border-blue-400 text-blue-400 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">Edit</a>
                                        <a href="{{ employee.get_delete_url }}" class="inline-block px-6 py-2 border-2 border-red-600 text-red-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">Delete</a>
                                    </td>
                                </tr class="bg-white border-b">
                                {% endfor %}

                                </tbody>


                            </table>
                            {% if is_paginated %}
                            <div class="flex justify-center">
  <nav aria-label="Page navigation example">
    <ul class="flex list-style-none">
        {% if page_obj.has_previous %}
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 focus:shadow-none"
          href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none"
          href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
      {% if page_obj.has_next %}
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none"
          href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
      {% endif %}
  </nav>
</div>
                                            </div>


                        </div>

                </div>

            </div>
            <!-- /End replace -->
        </div>
    </main>
</div>


{% endblock content %}

templates/employee_create.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}

{% block content %}
<div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <h3 class="text-gray-900 text-xl leading-tight font-medium mb-2">Create Employee</h3>
    <div class="mt-8 max-w-md">

            <form action="" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Save" class="inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out"/>

                <a href="{% url 'core:employee' %}" class="inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out">Cancel</a>
            </form>

    </div>
</div>
{% endblock content %}

templates/employee_delete.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}

{% block content %}
<div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <h3 class="text-gray-900 text-xl leading-tight font-medium mb-2">Delete Employee</h3>
    <div class="mt-8 max-w-md">

        <p>Are you sure you want to delete this employee?</p>

            <form action="" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Delete" class="inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out"/>

                <a href="{% url 'core:employee' %}" class="inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out">Cancel</a>
            </form>

    </div>
</div>
{% endblock content %}

templates/employee_detail.html
{% extends "base.html" %}

{% block content %}


<div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold tracking-tight text-gray-900">Employee Details</h1>
</div>

<div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="px-4 py-5 sm:px-6">
            <h3 class="text-lg font-medium leading-6 text-gray-900">Employee Basic Information</h3>
<!--            <p class="mt-1 max-w-2xl text-sm text-gray-500">Personal details information</p>-->
        </div>
        <div class="border-t border-gray-200">
            <dl>
                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Employee ID</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">{{ employee.emp_no }}</dd>
                </div>
                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">First name</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">{{ employee.first_name }}</dd>
                </div>
                <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Last Name</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">{{ employee.last_name }}</dd>
                </div>
                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Hire Date</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">{{ employee.hire_date }}</dd>
                </div>
                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Profile Picture</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                        <img src="{{ employee.imageURL|default:'/media_root/profile.png' }}" class="rounded-full w-32">
                    </dd>
                </div>
                <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Birth Date</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">{{ employee.birth_date }}</dd>
                </div>

                <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Attachments</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                        <ul role="list" class="divide-y divide-gray-200 rounded-md border border-gray-200">
                            <li class="flex items-center justify-between py-3 pl-3 pr-4 text-sm">
                                <div class="flex w-0 flex-1 items-center">
                                    <!-- Heroicon name: mini/paper-clip -->
                                    <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                        <path fill-rule="evenodd"
                                              d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z"
                                              clip-rule="evenodd"/>
                                    </svg>
                                    <span class="ml-2 w-0 flex-1 truncate">resume_back_end_developer.pdf</span>
                                </div>
                                <div class="ml-4 flex-shrink-0">
                                    <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">Download</a>
                                </div>
                            </li>
                            <li class="flex items-center justify-between py-3 pl-3 pr-4 text-sm">
                                <div class="flex w-0 flex-1 items-center">
                                    <!-- Heroicon name: mini/paper-clip -->
                                    <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                        <path fill-rule="evenodd"
                                              d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z"
                                              clip-rule="evenodd"/>
                                    </svg>
                                    <span class="ml-2 w-0 flex-1 truncate">coverletter_back_end_developer.pdf</span>
                                </div>
                                <div class="ml-4 flex-shrink-0">
                                    <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">Download</a>
                                </div>
                            </li>
                        </ul>
                    </dd>
                </div>
            </dl>
        </div>
    </div>
</div>
</div>




{% endblock content %}

templates/employee_list.html
{% extends "base.html" %}

{% block content %}
    <header class="bg-white shadow">
        <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold tracking-tight text-gray-900">Employee List</h1>
        </div>
    </header>
    <main>
        <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
            <!-- Replace with your content -->
            <div class="inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8 flex flex-col">

                        {% if messages %}
                        {% for message in messages %}

                        <div class="bg-green-100 rounded-lg py-5 px-6 mb-3 text-base text-green-700 inline-flex items-center w-full" role="alert">
                          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path fill="currentColor" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path>
                          </svg>
                          {{ message|safe }}
                        </div>
                        {% endfor %}
                        {% endif %}

                        <div class="overflow-hidden">
                            <h5 class="text-gray-900 text-xl leading-tight font-medium mb-2">Employee</h5>
                            <a type="button" class="inline-block px-6 py-2.5 bg-blue-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-500 hover:shadow-lg focus:bg-blue-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-600 active:shadow-lg transition duration-150 ease-in-out" href="{% url 'core:employee-add' %}">
+ Add Employee
</a>
                            <table class="min-w-full text-center">
                                <thead class="border-b bg-gray-500">
                                <tr>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Emp No.
                                    </th>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Firstname
                                    </th>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Lastname
                                    </th>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Hire Date
                                    </th>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Image
                                    </th>
                                    <th scope="col"
                                        class="text-sm font-medium text-white px-6 py-4">
                                        Action
                                    </th>
                                </tr>
                                </thead class="border-b">
                                <tbody>
                                {% for employee in object_list %}
                                <tr class="bg-white border-b">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        <a href="{{ employee.get_absolute_url }}">{{ employee.emp_no }}</a>
                                    </td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ employee.first_name }}
                                    </td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ employee.last_name }}
                                    </td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ employee.hire_date }}
                                    </td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        <img src="{{ employee.imageURL|default:'/media_root/profile.png' }}" class="h-12 w-12 rounded-full">
                                    </td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        <a href="{{ employee.get_update_url }}" class="inline-block px-6 py-2 border-2 border-blue-400 text-blue-400 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">Edit</a>
                                        <a href="{{ employee.get_delete_url }}" class="inline-block px-6 py-2 border-2 border-red-600 text-red-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">Delete</a>
                                    </td>
                                </tr class="bg-white border-b">
                                {% endfor %}

                                </tbody>


                            </table>
                            {% if is_paginated %}
                            <div class="flex justify-center">
  <nav aria-label="Page navigation example">
    <ul class="flex list-style-none">
        {% if page_obj.has_previous %}
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 focus:shadow-none"
          href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none"
          href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
      {% if page_obj.has_next %}
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none"
          href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
      {% endif %}
  </nav>
</div>
                                            </div>


                        </div>

                </div>

            </div>
            <!-- /End replace -->
        </div>
    </main>
</div>


{% endblock content %}

templates/employee_update.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}

{% block content %}
<div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <h3 class="text-gray-900 text-xl leading-tight font-medium mb-2">Update Employee</h3>
    <div class="mt-8 max-w-md">

            {% if messages %}
            {% for message in messages %}

            <div class="bg-green-100 rounded-lg py-5 px-6 mb-3 text-base text-green-700 inline-flex items-center w-full" role="alert">
              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path fill="currentColor" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path>
              </svg>
              {{ message|safe }}
            </div>
            {% endfor %}
            {% endif %}

            <form action="" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Save" class="inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out"/>

                <a href="{% url 'core:employee' %}" class="inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out">Cancel</a>
            </form>

    </div>
</div>
{% endblock content %}